language: ruby

rvm:
  - 2.1
  - 2.0.0
  - ruby-head

env:
  - "CHEF_VERSION="
  - "CHEF_VERSION='~> 11.14.2'"
  - "CHEF_VERSION='~> 11.4.4'"

bundler_args: --without guard

matrix:
  allow_failures:
    - rvm: ruby-head
